title: "E. R. Jormundsen"
email: contact@erjormundsen.com
description: "Official author site"
baseurl: ""
url: "https://www.erjormundsen.com"
twitter_username: erjormundsen
github_username: erjormundsen
author: "E. R. Jormundsen"

# Theme settings
# The theme is now local, so no 'remote_theme' or 'theme' is needed.

# Settings from upstream theme for compatibility
icon: /assets/images/icon-512.png
# markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 3
paginate_path: "/page/:num/"

# Custom settings
ignore_theme_config: true
hide_credits: true
hide_search: true
