title: "E. R. Jormundsen"
email: contact@erjormundsen.com
description: "Official author site"
baseurl: ""
url: "https://www.erjormundsen.com"
twitter_username: erjormundsen
github_username: erjormundsen
author: "E. R. Jormundsen"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

# Theme: set to 'hitchens'
# theme: hitchens-theme
remote_theme: patdryburgh/hitchens
ignore_theme_config: true
hide_credits: true
hide_search: true
